name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  PYTHONUTF8: 1
  FLET_CLI_NO_RICH_OUTPUT: 1
  UV_NO_PROGRESS: 1
jobs:
  build:
    name: build-windows
    runs-on: windows-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.17"

      - name: Install dependencies
        run: uv sync

      - name: Build Windows Binary
        run: uv run poe build-windows

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: windows-build-artifact
          path: build/windows
          if-no-files-found: error
          overwrite: false
